/// Flutter icons Icons_Mute
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icons_Mute
///      fonts:
///       - asset: fonts/Icons_Mute.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Icons_Mute {
  Icons_Mute._();

  static const _kFontFam = 'Icons_Mute';
  static const String _kFontPkg = null;

  static const IconData mute_fil_16 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
